IF OBJECT_ID('TRG_HOPDONG_AUDIT', 'TR') IS NOT NULL
    DROP TRIGGER TRG_HOPDONG_AUDIT;
GO

CREATE TRIGGER TRG_HOPDONG_AUDIT
ON HOPDONG
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (SELECT 1 FROM INSERTED) AND NOT EXISTS (SELECT 1 FROM DELETED)
    BEGIN
        INSERT INTO NHATKY (IDNGUOIDUNG, TENBANG, IDDULIEU, HANHDONG, THOIGIAN)
        SELECT NULL, 'HOPDONG', IDHOPDONG, 'THEM', GETDATE()
        FROM INSERTED;
    END
    ELSE IF EXISTS (SELECT 1 FROM INSERTED) AND EXISTS (SELECT 1 FROM DELETED)
    BEGIN
        INSERT INTO NHATKY (IDNGUOIDUNG, TENBANG, IDDULIEU, HANHDONG, THOIGIAN)
        SELECT NULL, 'HOPDONG', IDHOPDONG, 'SUA', GETDATE()
        FROM INSERTED;
    END
    ELSE IF EXISTS (SELECT 1 FROM DELETED)
    BEGIN
        INSERT INTO NHATKY (IDNGUOIDUNG, TENBANG, IDDULIEU, HANHDONG, THOIGIAN)
        SELECT NULL, 'HOPDONG', IDHOPDONG, 'HUY', GETDATE()
        FROM DELETED;
    END
END
GO

IF OBJECT_ID('TRG_THANHTOAN_AUDIT', 'TR') IS NOT NULL
    DROP TRIGGER TRG_THANHTOAN_AUDIT;
GO

CREATE TRIGGER TRG_THANHTOAN_AUDIT
ON THANHTOAN
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;

    IF EXISTS (SELECT 1 FROM INSERTED) AND NOT EXISTS (SELECT 1 FROM DELETED)
    BEGIN
        INSERT INTO NHATKY (IDNGUOIDUNG, TENBANG, IDDULIEU, HANHDONG, THOIGIAN)
        SELECT NULL, 'THANHTOAN', IDTHANHTOAN, 'THEM', GETDATE()
        FROM INSERTED;
    END
    ELSE IF EXISTS (SELECT 1 FROM INSERTED) AND EXISTS (SELECT 1 FROM DELETED)
    BEGIN
        INSERT INTO NHATKY (IDNGUOIDUNG, TENBANG, IDDULIEU, HANHDONG, THOIGIAN)
        SELECT NULL, 'THANHTOAN', i.IDTHANHTOAN,
               CASE WHEN i.TRANGTHAI = N'Đã xác nhận' THEN 'XACNHANTHANHTOAN' ELSE 'SUA' END,
               GETDATE()
        FROM INSERTED i;
    END
    ELSE IF EXISTS (SELECT 1 FROM DELETED)
    BEGIN
        INSERT INTO NHATKY (IDNGUOIDUNG, TENBANG, IDDULIEU, HANHDONG, THOIGIAN)
        SELECT NULL, 'THANHTOAN', IDTHANHTOAN, 'HUY', GETDATE()
        FROM DELETED;
    END
END
GO
